-- Rename BOOK_REVIEW_* to BOOK_REPORT_*
UPDATE notification_types SET code = 'BOOK_REPORT_CHECKED' WHERE code = 'BOOK_REVIEW_CHECKED';
UPDATE notification_types SET code = 'BOOK_REPORT_DEADLINE_24H_BEFORE' WHERE code = 'BOOK_REVIEW_DEADLINE_24H_BEFORE';
UPDATE notification_types SET code = 'BOOK_REPORT_DEADLINE_30M_BEFORE' WHERE code = 'BOOK_REVIEW_DEADLINE_30M_BEFORE';
