ALTER TABLE messages ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE chatting_rooms ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE room_rounds ADD COLUMN IF NOT EXISTS summary TEXT NULL;
